#!perl -w
use IPC::Open2;

`touch /tmp/started`;

$mypath = $ENV{PATH_INFO};

if ($mypath =~ /\/?([^\.]+)\./) {
  $mytype = $1
}


if ($mytype) {

`touch /tmp/forkking`;

  if (-e "/config/$mytype\_rml.ttl") {
  #	$pid = open2(my $chld_out, my $chld_in, "java -jar /opt/app/RMLStreamer.jar toFile -m ./config/$mytype\_rml.ttl -o ./data/triples/$mytype");
    $pid = open2(my $chld_out, my $chld_in, "/opt/java/openjdk/bin/java -jar /opt/app/RMLStreamer.jar toFile -m /config/$mytype\_rml.ttl -o /data/triples/$mytype");
  }
`touch /tmp/$pid`;

  waitpid $pid, 0;

  $pid = open2($chld_out,$chld_in, "cat /data/triples/$mytype/* > /data/triples/$mytype.ttl");
  $pid = open2($chld_out,$chld_in, "rm -rf /data/triples/$mytype");
};

`touch /tmp/finished`;

$pid = open2($chld_out,$chld_in, "cat /data/triples/$mytype/* > /data/triples/$mytype.ttl");
$pid = open2($chld_out,$chld_in, "rm -rf /data/triples/$mytype");

